=head1 NAME

REST::Google::Apps::EmailSettings - A Perl library to Google's RESTful Apps API

=head1 SYNOPSIS

  use REST::Google::Apps::EmailSettings

  $google = REST::Google::Apps::EmailSettings->new(
      domain   => 'company.com',
      username => 'admin',
      password => 'g00gl34pp5!'
  );

  $user->{'jsmith'} = $google->enableForwarding(
      username  => 'jsmith',
      forwardTo => 'joe@example.net'
  );

=head1 DESCRIPTION

REST::Google::Apps::EmailSettings provides a Perl interface to Google's
RESTful Apps API.

This module is currently a work-in-progress.  Please e-mail with problems,
bug fixes, comments and complaints.

=head1 CONSTRUCTOR

=over 4

=item new ( DOMAIN, USERNAME, PASSWORD )

Creates a new B<REST::Google::Apps::EmailSettings> object.  A domain parameter
is required.

Supplying authentication information to the constructor is optional , but needs
to happen either here or with a call to the B<authenticate> method.

B<Example>

  $google = REST::Google::Apps::EmailSettings->new(
      domain   => 'company.com',
      username => 'admin',
      password => 'g00gl34pp5!'
  );

=back

=head1 METHODS

=over 4

=item authenticate ( USERNAME, PASSWORD )

Authenticate a session.

B<Example>

  $google->authenticate(
      username => 'admin',
      password => 'g00gl34pp5!'
  )
  || die "Could not authenticate";

=item enableForwarding ( USERNAME, FORWARDTO, ACTION )

B<Example>

  $google->enableForwarding(
      username   => 'jsmith',
      forwareTo  => 'joe@example.net',
      action     => 'archive'
  )
  || die "Could not enable forwarding";

=item disableForwarding ( USERNAME )

B<Example>

  $google->disableForwarding( 'jsmith' );

=back

=head1 AUTHOR

Scott Schneider <sschneid@gmail.com>

=cut

