#!/usr/bin/perl

BEGIN { push @INC, '../lib'; }

unless ( $ARGV[0] ) {
    print "Usage: enablepop <user>\n";
    exit();
}

use YAML;
my $config = YAML::LoadFile( 'config.yaml' );

#--

use REST::Google::Apps::EmailSettings;

my $google = REST::Google::Apps::EmailSettings->new(
    domain => $config->{'domain'}
)
|| die "Could not construct\n";

$google->authenticate(
    username => $config->{'username'},
    password => $config->{'password'}
)
|| die "Could not authenticate\n";

use Data::Dumper;
print Dumper $google->enablePOP(
    username  => $ARGV[0]
);

