#!/usr/bin/perl

BEGIN { push @INC, '../lib'; }

unless ( $ARGV[2] ) {
    print "Usage: updateuser <user> <param> <value>\n";
    exit();
}

use YAML;
my $config = YAML::LoadFile( 'config.yaml' );

#--

use REST::Google::Apps::Provisioning;

my $google = REST::Google::Apps::Provisioning->new(
    domain => $config->{'domain'}
)
|| die "Could not construct\n";

$google->authenticate(
    username => $config->{'username'},
    password => $config->{'password'}
)
|| die "Could not authenticate\n";

use Data::Dumper;
print Dumper $google->updateUser(
    username => $ARGV[0],
    $ARGV[1] => $ARGV[2]
);

